App/routes/equipamento.py
from flask import render_template, Blueprint, request, redirect, url_for
from App.routes.auth.autenticar import admin_auth, admin_suporte_auth
from App.controllerWeb.equipamento import cadastrarEquipamento, listarEquipamentos, buscarEquipamentoId, atualizarEquipamento, removerEquipamento
from App.controllerWeb.area import listarAreas
from App.routes.utils import processar_mensagem, processar_resultado, processar_paginacao, processar_validacao, renderizar_com_mensagem

equipamento_route = Blueprint('equipamento_route', __name__, template_folder='templates/Equipamentos/')

# -------------------------- Funções Auxiliares ------------------------
CAMPOS_EQUIPAMENTO = ['nome', 'marca', 'quantidade', 'idArea']
VALIDACOES = {
    'nome': lambda nome: True if 3 <= len(nome) <= 100 else "O nome do equipamento deve ter entre 3 e 100 caracteres.",
    'marca': lambda marca: True if marca else "A marca do equipamento não pode estar vazia.",
}

def processar_dados(dados: dict) -> dict:
    return {campo: dados.get(campo, '').strip() for campo in CAMPOS_EQUIPAMENTO}

def validar(dados: dict) -> bool:
    return processar_validacao(dados, tipo="obrigatorio", validacoes_adicionais=VALIDACOES)

# =================== Listar Equipamentos ===================
@equipamento_route.route("/", methods=['GET'])
@admin_suporte_auth
def listar_Equipamento():
    page, per_page, search_query = request.args.get('page', 1, type=int), 10, request.args.get('search', '', type=str)
    equipamentos_dict = listarEquipamentos(search_query)
    if not isinstance(equipamentos_dict, dict):
        processar_mensagem(mensagem="Erro ao listar equipamentos. Verifique a conexão ou os parâmetros de pesquisa.", nivel="ERROR", tipo_flash="danger")
        return renderizar_com_mensagem('Equipamentos/listar.html', {'valores': [], 'total_items': 0, 'page': 1, 'per_page': per_page, 'search_query': search_query}, 'Erro ao listar equipamentos.', "ERROR", "danger")
    equipment_list = list(equipamentos_dict.items())
    equipamentos_paginated, total_items, total_pages, current_page, has_next, has_prev = processar_paginacao(equipment_list, page, per_page)
    return render_template('Equipamentos/listar.html', valores=equipamentos_paginated, total_items=total_items, total_pages=total_pages, page=current_page, per_page=per_page, search_query=search_query, has_next=has_next, has_prev=has_prev)

# =================== Cadastrar Equipamento ===================
@equipamento_route.route("/cadastrar", methods=['GET', 'POST'])
@admin_suporte_auth
def cadastrar_Equipamento():
    if request.method == 'POST':
        dados = request.form.to_dict()
        if not validar(dados): 
            processar_mensagem(mensagem="Erro de validação. Verifique os campos obrigatórios.", nivel="ERROR", tipo_flash="danger")
            return render_template('Equipamentos/cadastrar.html', mensagem="Erro de validação. Verifique os campos obrigatórios.", valores=listarAreas())
        dados_processados = processar_dados(dados)
        resultado = cadastrarEquipamento(dados_processados['idArea'], dados_processados)
        if processar_resultado(resultado, f"Equipamento {dados['nome']} cadastrado com sucesso!", "Erro ao cadastrar equipamento. Verifique os dados e tente novamente."):
            return redirect(url_for('equipamento_route.listar_Equipamento'))
    return render_template('Equipamentos/cadastrar.html', valores=listarAreas())

# =================== Atualizar Equipamento ===================
@equipamento_route.route('/editar/<int:id>', methods=['GET', 'POST'])
@admin_suporte_auth
def editar_Equipamento(id):
    equipamento = buscarEquipamentoId(id)
    if not equipamento or 'error' in equipamento:
        processar_mensagem(mensagem=f"Equipamento com ID {id} não encontrado. Verifique o ID e tente novamente.", nivel="WARNING", tipo_flash="warning")
        return redirect(url_for('equipamento_route.listar_Equipamento'))
    if request.method == 'POST':
        dados = request.form.to_dict()
        if not validar(dados):
            return render_template('Equipamentos/editar.html', equipamento=equipamento, valores=listarAreas())
        dados_processados = processar_dados(dados)
        result = atualizarEquipamento(id, **dados_processados)
        if processar_resultado(result, f"Equipamento {dados['nome']} atualizado com sucesso!", "Erro ao atualizar equipamento. Verifique os dados e tente novamente."):
            return redirect(url_for('equipamento_route.listar_Equipamento'))
    return render_template('Equipamentos/editar.html', equipamento=equipamento, valores=listarAreas())

# =================== Remover Equipamento ===================
@equipamento_route.route('/remover/<int:id>', methods=['GET'])
@admin_auth
def remover_Equipamento(id):
    try:
        result = removerEquipamento(id)
        if not processar_resultado(result, f"Equipamento com ID {id} removido com sucesso!", f"Erro ao remover o equipamento com ID {id}. Verifique o ID e tente novamente."):
            raise Exception(f"Falha ao remover o equipamento com ID {id}.")
    except Exception as e:
        processar_mensagem(mensagem=f"Erro ao remover: {str(e)}. Tente novamente mais tarde.", nivel="ERROR", tipo_flash="danger", contexto_extra={'id': id})
    return redirect(url_for('equipamento_route.listar_Equipamento'))

# =================== Ocupado Equipamento ===================
@equipamento_route.route("/ocupado", methods=['GET', 'POST'])
@admin_suporte_auth
def ocupado_Equipamento():    
    return render_template('Equipamentos/ocupado.html')

App/templates/Equipamentos/cadastrar.html
{% extends "base.html" %}

{% block title %}Gestão de Equipamentos - Cadastro de Equipamentos{% endblock %}

{% block content %}

<div class="container-fluid my-2">
    <div class="card shadow-sm p-3 rounded-3" style="box-shadow: inherit !important; transform: none !important;">

        <!-- Formulário para adicionar um novo equipamento -->
        <form id="formCadastroEquipamento" action="{{ url_for('equipamento_route.cadastrar_Equipamento') }}"
            method="POST" class="form-equipamento needs-validation" novalidate>
            <h2 class="text-center mb-4 fw-bold text-primary">Cadastro de Equipamento</h2>

            <div class="d-flex justify-content-end align-items-center mb-4">
                <a href="{{ url_for('equipamento_route.listar_Equipamento') }}" class="btn btn-success btn-sm">
                    <i class="fas fa-list"></i> Lista de Equipamentos
                </a>
                <a href="{{ url_for('equipamento_route.ocupado_Equipamento') }}" class="btn btn-success btn-sm">
                    <i class="fas fa-list"></i> Equipamentos Ocupados
                </a>
            </div>

            <fieldset>

                <div class="row g-2">
                    <!-- Área -->
                    <div class="col-md-6 mb-3">
                        <label for="idArea" class="form-label text-dark fs-5">Área:</label>
                        <select id="idArea" name="idArea" class="form-select shadow-sm" required
                            aria-describedby="areaFeedback">
                            <option value="" disabled selected>Selecione a Área</option>
                            {% for area, id in valores.items() %}
                            <option value="{{ id }}">{{ area }}</option>
                            {% endfor %}
                        </select>
                        <div id="areaFeedback" class="invalid-feedback">Por favor, selecione uma área.</div>
                    </div>

                    <!-- Nome do Equipamento -->
                    <div class="col-md-6 mb-3">
                        <label for="nome" class="form-label text-dark fs-5">Nome do Equipamento:</label>
                        <input type="text" id="nome" name="nome" required maxlength="100" class="form-control shadow-sm"
                            placeholder="Nome do Equipamento" pattern="^[a-zA-Z0-9\s]+$" aria-required="true"
                            aria-describedby="nomeFeedback">
                        <div id="nomeFeedback" class="invalid-feedback">Por favor, preencha o nome do equipamento
                            corretamente (apenas letras, números e espaços).</div>
                    </div>

                    <!-- Marca do Equipamento -->
                    <div class="col-md-6 mb-3">
                        <label for="marca" class="form-label text-dark fs-5">Marca do Equipamento:</label>
                        <input type="text" id="marca" name="marca" required maxlength="100"
                            class="form-control shadow-sm" placeholder="Marca do Equipamento"
                            pattern="^[a-zA-Z0-9\s]+$" aria-required="true" aria-describedby="marcaFeedback">
                        <div id="marcaFeedback" class="invalid-feedback">Por favor, preencha a marca do equipamento
                            corretamente (apenas letras, números e espaços).</div>
                    </div>

                    <!-- Quantidade -->
                    <div class="col-md-6 mb-3">
                        <label for="quantidade" class="form-label text-dark fs-5">Quantidade:</label>
                        <input type="number" id="quantidade" name="quantidade" required min="1"
                            class="form-control shadow-sm" placeholder="Quantidade" aria-required="true"
                            aria-describedby="quantidadeFeedback">
                        <div id="quantidadeFeedback" class="invalid-feedback">Por favor, informe a quantidade
                            corretamente.</div>
                    </div>
                </div>

                <!-- Botões de Ação -->
                <div class="d-flex justify-content-between mt-3">
                    <button type="reset"
                        class="btn btn-outline-secondary btn-lg w-45 rounded-3 shadow-sm d-flex align-items-center justify-content-center">
                        <i class="bi bi-x-circle me-2"></i> Limpar
                    </button>
                    <button type="submit"
                        class="btn btn-primary btn-lg w-45 rounded-3 shadow-sm d-flex align-items-center justify-content-center"
                        id="submitBtn" disabled>
                        <i class="bi bi-check-circle me-2"></i> Cadastrar Equipamento
                    </button>
                </div>
            </fieldset>
        </form>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const form = document.getElementById("formCadastroEquipamento");
        const submitBtn = document.getElementById("submitBtn");

        if (form && submitBtn) {
            form.addEventListener("input", function () {
                submitBtn.disabled = !form.checkValidity();
            });
        }
    });
</script>

{% endblock %}

App/templates/Equipamentos/editar.html
{% extends "base.html" %}

{% block title %}Gestão de Equipamentos - Editar Equipamento{% endblock %}

{% block content %}
<div class="container-fluid my-2">
    <div class="card shadow-sm p-3 rounded-3" style="box-shadow: inherit !important; transform: none !important;">

        <!-- Formulário para editar equipamento -->
        <form id="formEditarEquipamento" action="{{ url_for('equipamento_route.editar_Equipamento', id=equipamento.idEquipamento) }}" method="POST" class="form-equipamento needs-validation" novalidate>
            <h2 class="text-center mb-4 fw-bold text-primary">Edição de Equipamento</h2>

            <div class="d-flex justify-content-end align-items-center mb-4">
                <a href="{{ url_for('equipamento_route.listar_Equipamento') }}" class="btn btn-success btn-sm">
                    <i class="fas fa-list"></i> Lista de Equipamentos
                </a>
                <a href="{{ url_for('equipamento_route.ocupado_Equipamento') }}" class="btn btn-success btn-sm">
                    <i class="fas fa-list"></i> Equipamentos Ocupados
                </a>
            </div>

            <fieldset>
                <input type="hidden" id="id" name="id" value="{{ equipamento.idEquipamento }}" />

                <div class="row g-2">
                    <!-- Nome do Equipamento -->
                    <div class="col-md-6 mb-3">
                        <label for="nome" class="form-label text-dark fs-5">Nome do Equipamento:</label>
                        <input type="text" id="nome" name="nome" value="{{ equipamento.nome }}" required maxlength="100" class="form-control shadow-sm" placeholder="Nome do Equipamento" pattern="^[a-zA-Z0-9\s]+$" aria-describedby="nomeFeedback">
                        <div id="nomeFeedback" class="invalid-feedback">Por favor, preencha o nome do equipamento corretamente (apenas letras, números e espaços).</div>
                    </div>

                    <!-- Marca do Equipamento -->
                    <div class="col-md-6 mb-3">
                        <label for="marca" class="form-label text-dark fs-5">Marca do Equipamento:</label>
                        <input type="text" id="marca" name="marca" value="{{ equipamento.marca }}" required maxlength="100" class="form-control shadow-sm" placeholder="Marca do Equipamento" pattern="^[a-zA-Z0-9\s]+$" aria-describedby="marcaFeedback">
                        <div id="marcaFeedback" class="invalid-feedback">Por favor, preencha a marca do equipamento corretamente (apenas letras, números e espaços).</div>
                    </div>

                    <!-- Quantidade -->
                    <div class="col-md-6 mb-3">
                        <label for="quantidade" class="form-label text-dark fs-5">Quantidade:</label>
                        <input type="number" id="quantidade" name="quantidade" value="{{ equipamento.quantidade }}" required min="1" class="form-control shadow-sm" placeholder="Quantidade" aria-describedby="quantidadeFeedback">
                        <div id="quantidadeFeedback" class="invalid-feedback">Por favor, informe a quantidade corretamente.</div>
                    </div>

                    <!-- Área -->
                    <div class="col-md-6 mb-3">
                        <label for="idArea" class="form-label text-dark fs-5">Área:</label>
                        <select id="idArea" name="idArea" class="form-select shadow-sm" required aria-describedby="areaFeedback">
                            <option value="" disabled>Selecione a Área</option>
                            {% for area, id in valores.items() %}
                                <option value="{{ id }}" {% if equipamento.idArea == id %}selected{% endif %}>{{ area }}</option>
                            {% endfor %}
                        </select>
                        <div id="areaFeedback" class="invalid-feedback">Por favor, selecione uma área.</div>
                    </div>
                </div>

                <!-- Botões de Ação -->
                <div class="d-flex justify-content-between mt-3">
                    <!-- Botão de Voltar -->
                    <a href="javascript:history.back()" class="btn btn-secondary btn-lg w-45 rounded-3 shadow-sm d-flex align-items-center justify-content-center">
                        <i class="bi bi-arrow-left-circle me-2"></i> Voltar
                    </a>

                    <!-- Botão de Salvar -->
                    <button type="submit" class="btn btn-primary btn-lg w-45 rounded-3 shadow-sm d-flex align-items-center justify-content-center" id="submitBtn" disabled>
                        <i class="bi bi-check-circle me-2"></i> Salvar Alterações
                    </button>
                </div>
            </fieldset>
        </form>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const form = document.getElementById("formEditarEquipamento");
        const submitBtn = document.getElementById("submitBtn");

        if (form && submitBtn) {
            form.addEventListener("input", function () {
                submitBtn.disabled = !form.checkValidity();
            });
        }
    });
</script>

{% endblock %}

App/templates/Equipamentos/listar.html
{% extends "base.html" %}

{% block title %}Gestão de Equipamentos - Mapa de Sala{% endblock %}

{% block content %}

<div class="container-fluid my-2">
    <div class="card shadow-sm p-4 rounded-3" style="box-shadow: inherit !important; transform: none !important;">
        <h2 class="text-center mb-4 fw-bold text-primary">Lista de Equipamentos</h2>

        <div class="d-flex justify-content-end align-items-center mb-4">
            <a href="{{ url_for('equipamento_route.ocupado_Equipamento') }}" class="btn btn-success btn-sm">
                <i class="fas fa-list"></i> Equipamentos Ocupados
            </a>
            <a href="{{ url_for('equipamento_route.cadastrar_Equipamento') }}" class="btn btn-success btn-sm">
                <i class="fas fa-plus"></i> Cadastrar Equipamento
            </a>
        </div>
        <br>

        <fieldset>
            <legend class="visually-hidden">Detalhes das listas de Equipamentos</legend>

            <!-- Formulário de Pesquisa -->
            <form method="GET" action="{{ url_for('equipamento_route.listar_Equipamento') }}" class="search-form"
                role="search" aria-labelledby="searchForm">
                <div class="input-group mb-1 mb-md-0">
                    <input class="input" required autocomplete="off" type="text" name="search" id="search"
                        placeholder=" " value="{{ search_query }}" aria-label="Pesquisar equipamentos" />
                    <label class="label" for="search">Pesquisar</label>
                    <div class="input-wrapper">
                        <svg id="loadingIcon" class="d-none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"
                            fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                            stroke-linejoin="round" aria-hidden="true">
                            <circle cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" fill="none"
                                class="animate-spin"></circle>
                        </svg>
                    </div>
                </div>
                <button type="button" class="btn btn-secondary ml-2" id="clearSearch"
                    aria-label="Limpar pesquisa">Limpar</button>
            </form>

            <!-- Botões principais -->
            <div class="d-flex justify-content-between align-items-center mb-4">
                <button id="toggleTable" class="btn btn-info btn-sm"
                    aria-label="Mostrar/Esconder lista de equipamentos">
                    <i class="fas fa-list"></i> Lista de Equipamentos
                </button>
            </div>

            <!-- Tabela de Equipamentos -->
            <div id="tableContainer" class="table-responsive d-none mt-4">
                <table class="table table-striped table-hover table-bordered align-middle rounded shadow-sm">
                    <caption class="visually-hidden">Tabela com lista de equipamentos</caption>
                    <thead class="table-dark text-center">
                        <tr>
                            <th style="width: 70%;">Nome</th>
                            <th class="text-center" style="width: 30%;">Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for equipamento in valores %}
                        <tr>
                            <td class="text-start">{{ equipamento[0] }}</td>
                            <td class="text-center">
                                <a href="/equipamento/editar/{{ equipamento[1] }}" class="btn btn-primary btn-sm">
                                    <i class="fas fa-edit"></i> Editar
                                </a>
                                {% if session.get('usuario') and session['nivel_acesso'] == 'admin' %}
                                <button class="btn btn-danger btn-sm"
                                    onclick="confirmRemove('{{ equipamento[1] }}', '{{ equipamento[0] }}')">
                                    <i class="fas fa-trash"></i> Remover
                                </button>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>


                    <!-- Paginação -->
                    <nav aria-label="Paginação">
                        <ul class="pagination justify-content-center">
                            {% if page > 1 %}
                            <li class="page-item">
                                <a class="page-link"
                                    href="{{ url_for('equipamento_route.listar_Equipamento', page=page - 1, search=search_query) }}">Anterior</a>
                            </li>
                            {% endif %}
                            <li class="page-item disabled">
                                <span class="page-link">Página {{ page }} de {{ (total_items // per_page) + (1 if
                                    total_items % per_page > 0 else 0) }}</span>
                            </li>
                            {% if page * per_page < total_items %} <li class="page-item">
                                <a class="page-link"
                                    href="{{ url_for('equipamento_route.listar_Equipamento', page=page + 1, search=search_query) }}">Próxima</a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>

                <!-- Modal de Confirmação de Remoção -->
                <div class="modal fade" id="confirmModal" tabindex="-1" aria-labelledby="confirmModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="confirmModalLabel">Confirmar Remoção</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Fechar"></button>
                            </div>
                            <div class="modal-body">
                                Tem certeza que deseja remover o equipamento "<span id="equipmentName"></span>"?
                                Esta ação
                                não pode ser desfeita.
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary"
                                    data-bs-dismiss="modal">Cancelar</button>
                                <button type="button" class="btn btn-danger"
                                    id="confirmRemoveButton">Remover</button>
                            </div>
                        </div>
                    </div>
                </div>
        </fieldset>
    </div>
</div>

<script>
    // Exibir modal de remoção
    function confirmRemove(id, nome) {
        document.getElementById('equipmentName').textContent = nome;
        const modal = new bootstrap.Modal(document.getElementById('confirmModal'));
        modal.show();

        document.getElementById('confirmRemoveButton').onclick = function () {
            window.location.href = `/equipamento/remover/${id}`;
        };
    }

    // Alternar visibilidade da tabela
    document.addEventListener('DOMContentLoaded', () => {
        const toggleTableBtn = document.getElementById('toggleTable');
        const tableContainer = document.getElementById('tableContainer');

        // Mantém a visibilidade da tabela entre sessões com localStorage
        if (localStorage.getItem('tableVisible') === 'true') {
            tableContainer.classList.remove('d-none');
        }

        toggleTableBtn.addEventListener('click', () => {
            tableContainer.classList.toggle('d-none');
            localStorage.setItem('tableVisible', !tableContainer.classList.contains('d-none'));
        });
    });

    // Feedback visual ao pesquisar
    const searchInput = document.getElementById('search');
    const loadingIcon = document.getElementById('loadingIcon');

    searchInput.addEventListener('input', () => {
        loadingIcon.classList.remove('d-none');
    });

</script>
{% endblock %}